# Generated by Django 6.0.3 on 2026-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_info',
            field=models.CharField(blank=True, default='Your order has been received and is being processed.', max_length=512),
        ),
    ]
